name: Build GB Studio ROM and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build GB Studio
        run: |
          git clone https://github.com/chrismaltby/gb-studio.git
          cd gb-studio
          yarn
          npm run make:cli
          yarn link
          chmod 777 /usr/local/bin/gb-studio-cli
          cd ..

      - name: Export Project and Make ROM
        run: |
          cd gb-studio
          gb-studio-cli make:rom ../"Undertale GB Main.gbsproj" out/game.gb

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: game-rom
          path: gb-studio/out/game.gb

      - name: Get commit info
        run: echo "::set-output name=commit::$(git log -1 --pretty=format:'%h - %an, %s')"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Commit Info:
            ${{ needs.build.outputs.commit }}
          draft: false
          prerelease: false

      - name: Download Artifact
        uses: actions/download-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          name: game-rom
          path: game-rom

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v3
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./game-rom/game.gb
          asset_name: game.gb
          asset_content_type: application/octet-stream
